name: fechar issue

on:
  pull_request:
    types: [opened, reopened]

jobs:
  fechar_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar repositório
      uses: actions/checkout@v2

    - name: Fechar issue referenciada
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        corpo_pr=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
        numeros_issues=$(echo "$corpo_pr" | grep -oE '#[0-9]+' | tr -d '#')

        for numero_issue in $numeros_issues; do
          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$numero_issue \
            -d '{"state": "closed"}'
        done
